version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - PHP_FPM_INSTALL_PGSQL=false
            - PHP_FPM_INSTALL_BCMATH=true
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "5173:80"
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mariadb:10.5
        container_name: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ""         # Empty password for root
            MYSQL_DATABASE: laravel_mastery_hub
            MYSQL_USER: root
            MYSQL_PASSWORD: ""              # Empty password for root user
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
