version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: laravel-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_mastery_hub
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network
        ports:
            - "3306:3306"


        nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
