<?php

use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/tobase',[OrderController::class,'index'])->name('tobase');

Route::get('/test-role', function () {
    return 'Testing role middleware';
})->middleware('role:admin');


// Route for admin dashboard, only accessible by users with 'admin' role
Route::get('/admin', function () {
    return view('admin.dashboard');
})->middleware('role:admin');  // Only accessible by admin users

// Route for the dashboard, requires authentication and email verification
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Group of routes requiring authentication
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Resource routes for posts, automatically adds routes for index, create, store, show, edit, update, destroy
Route::resource('posts', PostController::class);

// Authentication routes generated by Laravel Breeze
require __DIR__.'/auth.php';
